import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "./Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${geistSans.variable} ${geistMono.variable}
          antialiased
          bg-gray-50
        `}
      >
        {/* Fixed / Sticky Navbar safe */}
        <Navbar />

        {/* Page Wrapper */}
        <main
          className="
            min-h-[calc(100vh-64px)]
            pt-16
            px-3 sm:px-6 lg:px-8
          "
        >
          {children}
        </main>
      </body>
    </html>
  );
}
